/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    BackgroundRemoval: typeof import('./src/components/BackgroundRemoval.vue')['default']
    Base64Code: typeof import('./src/components/Base64Code.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    Button1: typeof import('./src/components/common/Button1.vue')['default']
    ConnectWallet: typeof import('./src/components/modal/ConnectWallet.vue')['default']
    CreateAccount: typeof import('./src/components/CreateAccount.vue')['default']
    GeoIP: typeof import('./src/components/GeoIP.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HexNumberConvert: typeof import('./src/components/HexNumberConvert.vue')['default']
    JsonFormat: typeof import('./src/components/JsonFormat.vue')['default']
    PasswordGenerate: typeof import('./src/components/PasswordGenerate.vue')['default']
    PrivateKeyReverse: typeof import('./src/components/PrivateKeyReverse.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignMessage: typeof import('./src/components/SignMessage.vue')['default']
    Test: typeof import('./src/components/common/test.vue')['default']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    UnixTimestamp: typeof import('./src/components/UnixTimestamp.vue')['default']
    URLCode: typeof import('./src/components/URLCode.vue')['default']
  }
}
